// <auto-generated />
using System;
using Habitia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Habitia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818192829_CoolDownCodigoVerificacion")]
    partial class CoolDownCodigoVerificacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Habitia.Models.Acceso.Acceso", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TF_FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TF_FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TN_IdAutorizacion")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdVehiculo")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVisitante")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TF_FechaIngreso");

                    b.HasIndex("TF_FechaSalida");

                    b.HasIndex("TN_IdAutorizacion")
                        .IsUnique()
                        .HasFilter("[TN_IdAutorizacion] IS NOT NULL");

                    b.HasIndex("TN_IdVehiculo");

                    b.HasIndex("TN_IdVisitante");

                    b.HasIndex("TN_IdVivienda");

                    b.ToTable("THBT_A_Acceso");
                });

            modelBuilder.Entity("Habitia.Models.Acceso.Autorizacion", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TF_FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TF_FechaVisita")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVisitante")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_Codigo")
                        .IsUnique();

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TF_FechaVencimiento");

                    b.HasIndex("TN_Estado");

                    b.HasIndex("TN_IdVisitante");

                    b.HasIndex("TN_IdVivienda");

                    b.ToTable("THBT_A_Autorizacion");
                });

            modelBuilder.Entity("Habitia.Models.Acceso.Vehiculo", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TC_Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TC_Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TN_IdVisitante")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdVisitante");

                    b.ToTable("THBT_A_Vehiculo");
                });

            modelBuilder.Entity("Habitia.Models.Acceso.Visitante", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TC_Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TN_TipoIdentificacion")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_A_Visitante");
                });

            modelBuilder.Entity("Habitia.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC_Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TC_FotoPerfil")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TC_Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TC_Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_TipoIdentificacion")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("THBT_A_Usuario", (string)null);
                });

            modelBuilder.Entity("Habitia.Models.AreaComun", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TN_AnticipacionMinima")
                        .HasColumnType("int");

                    b.Property<int>("TN_Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdTipo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdTipo");

                    b.ToTable("THBT_A_AreaComun");
                });

            modelBuilder.Entity("Habitia.Models.AreaComunFoto", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TN_IdAreaComun")
                        .HasColumnType("int");

                    b.Property<int>("TN_Orden")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdAreaComun");

                    b.ToTable("THBT_A_AreaComunFoto");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.CategoriaDocumento", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_Nombre")
                        .IsUnique();

                    b.ToTable("THBT_CAT_CategoriaDocumento");

                    b.HasData(
                        new
                        {
                            TN_Id = 1,
                            TB_Estado = true,
                            TC_Nombre = "Reglamentos"
                        },
                        new
                        {
                            TN_Id = 2,
                            TB_Estado = true,
                            TC_Nombre = "Actas"
                        },
                        new
                        {
                            TN_Id = 3,
                            TB_Estado = true,
                            TC_Nombre = "Comunicados"
                        },
                        new
                        {
                            TN_Id = 4,
                            TB_Estado = true,
                            TC_Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.THBT_CAT_CategoriaPublicacion", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_CAT_CategoriaPublicacion");

                    b.HasData(
                        new
                        {
                            TN_Id = 1,
                            TB_Estado = true,
                            TC_Nombre = "Muebles y hogar"
                        },
                        new
                        {
                            TN_Id = 2,
                            TB_Estado = true,
                            TC_Nombre = "Electrodomésticos"
                        },
                        new
                        {
                            TN_Id = 3,
                            TB_Estado = true,
                            TC_Nombre = "Ropa y accesorios"
                        },
                        new
                        {
                            TN_Id = 4,
                            TB_Estado = true,
                            TC_Nombre = "Alimentos y bebidas"
                        },
                        new
                        {
                            TN_Id = 5,
                            TB_Estado = true,
                            TC_Nombre = "Servicios del hogar"
                        },
                        new
                        {
                            TN_Id = 6,
                            TB_Estado = true,
                            TC_Nombre = "Cuidado personal"
                        },
                        new
                        {
                            TN_Id = 7,
                            TB_Estado = true,
                            TC_Nombre = "Clases y tutorías"
                        },
                        new
                        {
                            TN_Id = 8,
                            TB_Estado = true,
                            TC_Nombre = "Mascotas"
                        },
                        new
                        {
                            TN_Id = 9,
                            TB_Estado = true,
                            TC_Nombre = "Tecnología"
                        },
                        new
                        {
                            TN_Id = 10,
                            TB_Estado = true,
                            TC_Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.TipoArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("THBT_CAT_TipoArea");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.TipoMantenimiento", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_Nombre")
                        .IsUnique();

                    b.ToTable("THBT_CAT_TipoMantenimiento");
                });

            modelBuilder.Entity("Habitia.Models.CodigoVerificacion", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Invalidado")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_Usado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TF_FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TF_FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TF_UltimoReenvioUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_CiclosFallidos")
                        .HasColumnType("int");

                    b.Property<int>("TN_Intentos")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.ToTable("THBT_A_CodigoVerificacion");
                });

            modelBuilder.Entity("Habitia.Models.DisponibilidadArea", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_Reservado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TF_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TF_HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TF_HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("TN_AnticipacionMinima")
                        .HasColumnType("int");

                    b.Property<int>("TN_Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdAreaComun")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdAreaComun");

                    b.ToTable("THBT_A_DisponibilidadArea");
                });

            modelBuilder.Entity("Habitia.Models.Documentos.Asamblea", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Lugar")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TC_Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("TF_FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_Modalidad")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TF_FechaHora");

                    b.HasIndex("TN_Estado");

                    b.ToTable("THBT_A_Asamblea");
                });

            modelBuilder.Entity("Habitia.Models.Documentos.Documento", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Archivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TC_Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TC_NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TF_FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_IdCategoria")
                        .HasColumnType("int");

                    b.Property<long>("TN_Tamano")
                        .HasColumnType("bigint");

                    b.HasKey("TN_Id");

                    b.HasIndex("TB_Estado");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TN_IdCategoria");

                    b.ToTable("THBT_A_Documento");
                });

            modelBuilder.Entity("Habitia.Models.Documentos.DocumentoAsamblea", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<DateTime>("TF_FechaAsociacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_IdAsamblea")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdDocumento")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdDocumento");

                    b.HasIndex("TN_IdAsamblea", "TN_IdDocumento")
                        .IsUnique();

                    b.ToTable("THBT_A_DocumentoAsamblea");
                });

            modelBuilder.Entity("Habitia.Models.Documentos.ParticipanteAsamblea", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Asistio")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_Confirmado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_IdAsamblea")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TN_IdAsamblea", "TC_IdUsuario")
                        .IsUnique();

                    b.ToTable("THBT_A_ParticipanteAsamblea");
                });

            modelBuilder.Entity("Habitia.Models.ExpiracionReserva", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<int>("TN_Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_Tipo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_A_ExpiracionReserva");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_Cargo", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_AplicaIva")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_RecargoAplicado")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_RecargoProgramado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TC_FrecuenciaRecargo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TC_IdLote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC_IdResidente")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TF_FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TF_FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TF_UltimaAplicacionRecargo")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_IdEstadoCargo")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdTipoCargo")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdTipoRecargo")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.Property<decimal>("TN_MontoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TN_MontoIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TN_MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TN_ValorRecargo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdResidente");

                    b.HasIndex("TF_FechaVencimiento");

                    b.HasIndex("TN_IdEstadoCargo");

                    b.HasIndex("TN_IdTipoCargo");

                    b.HasIndex("TN_IdTipoRecargo");

                    b.HasIndex("TN_IdVivienda");

                    b.ToTable("THBT_A_Cargo");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_CargoRecurrente", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_AplicaIva")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_AplicarATodos")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_RecargoProgramado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TC_Frecuencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TC_FrecuenciaRecargo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("TF_FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TF_UltimaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_IdTipoCargo")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdTipoRecargo")
                        .HasColumnType("int");

                    b.Property<decimal>("TN_MontoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TN_ValorRecargo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TN_Id");

                    b.HasIndex("TB_Estado");

                    b.HasIndex("TN_IdTipoCargo");

                    b.HasIndex("TN_IdTipoRecargo");

                    b.ToTable("THBT_A_CargoRecurrente");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_CargoRecurrenteResidente", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_IdResidente")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TN_IdCargoRecurrente")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdResidente");

                    b.HasIndex("TN_IdVivienda");

                    b.HasIndex("TN_IdCargoRecurrente", "TC_IdResidente", "TN_IdVivienda")
                        .IsUnique()
                        .HasFilter("[TN_IdVivienda] IS NOT NULL");

                    b.ToTable("THBT_A_CargoRecurrenteResidente");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_ConfiguracionPago", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_EfectivoHabilitado")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_SinpeHabilitado")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_TarjetaHabilitado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_IbanTarjeta")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("TC_NumeroSinpe")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TC_TitularSinpe")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TC_TitularTarjeta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("TF_FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_A_ConfiguracionPago");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_Pago", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_MotivoRechazo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TC_RutaComprobante")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("TF_FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_IdCargo")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdMetodoPago")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdCargo");

                    b.HasIndex("TN_IdMetodoPago");

                    b.ToTable("THBT_A_Pago");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_Recargo", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TF_FechaAplicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_IdCargo")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdTipoRecargo")
                        .HasColumnType("int");

                    b.Property<decimal>("TN_MontoAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TN_Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdCargo");

                    b.HasIndex("TN_IdTipoRecargo");

                    b.ToTable("THBT_A_Recargo");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_CAT_EstadoCargo", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_CAT_EstadoCargo");

                    b.HasData(
                        new
                        {
                            TN_Id = 1,
                            TC_Nombre = "Pendiente"
                        },
                        new
                        {
                            TN_Id = 2,
                            TC_Nombre = "En revisión"
                        },
                        new
                        {
                            TN_Id = 3,
                            TC_Nombre = "Pagado"
                        },
                        new
                        {
                            TN_Id = 4,
                            TC_Nombre = "Vencido"
                        });
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_CAT_MetodoPago", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_CAT_MetodoPago");

                    b.HasData(
                        new
                        {
                            TN_Id = 1,
                            TC_Nombre = "Efectivo"
                        },
                        new
                        {
                            TN_Id = 2,
                            TC_Nombre = "Tarjeta"
                        },
                        new
                        {
                            TN_Id = 3,
                            TC_Nombre = "SINPE"
                        });
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_CAT_TipoCargo", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_Nombre")
                        .IsUnique();

                    b.ToTable("THBT_CAT_TipoCargo");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_CAT_TipoRecargo", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_CAT_TipoRecargo");

                    b.HasData(
                        new
                        {
                            TN_Id = 1,
                            TC_Nombre = "Fijo"
                        },
                        new
                        {
                            TN_Id = 2,
                            TC_Nombre = "Porcentaje"
                        });
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_CAT_TipoTarjeta", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_CAT_TipoTarjeta");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_H_Cargo", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_IdUsuarioCambio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TF_FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_IdCargo")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdEstadoCargoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdEstadoCargoNuevo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_H_Cargo");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_H_ConfiguracionPago", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_EfectivoHabilitado")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_SinpeHabilitado")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_TarjetaHabilitado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_IbanTarjeta")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("TC_IdUsuarioCambio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC_NumeroSinpe")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TC_TitularSinpe")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TC_TitularTarjeta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("TF_FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_IdConfiguracionPago")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_H_ConfiguracionPago");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_H_Pago", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Aprobado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_IdUsuarioCambio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC_MotivoRechazo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("TF_FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_IdPago")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_H_Pago");
                });

            modelBuilder.Entity("Habitia.Models.ImagenPublicacion", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TN_IdPublicacion")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdPublicacion");

                    b.ToTable("THBT_A_ImagenPublicacion");
                });

            modelBuilder.Entity("Habitia.Models.Incidencia", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_ImagenUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TC_Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TF_FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdAreaComun")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.Property<int?>("TN_Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("TN_Responsabilidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_Tipo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TF_FechaRegistro");

                    b.HasIndex("TN_Estado");

                    b.HasIndex("TN_IdAreaComun");

                    b.HasIndex("TN_IdVivienda");

                    b.HasIndex("TN_Responsabilidad");

                    b.ToTable("THBT_A_Incidencia");
                });

            modelBuilder.Entity("Habitia.Models.Mantenimiento", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TC_IdPersonalAsignado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("TF_FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TF_FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdAreaComun")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdIncidencia")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdTipo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdPersonalAsignado");

                    b.HasIndex("TN_Estado");

                    b.HasIndex("TN_IdAreaComun");

                    b.HasIndex("TN_IdIncidencia")
                        .IsUnique();

                    b.HasIndex("TN_IdTipo");

                    b.ToTable("THBT_A_Mantenimiento");
                });

            modelBuilder.Entity("Habitia.Models.PersonalTipoMantenimiento", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_IdPersonal")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TN_IdTipo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdTipo");

                    b.HasIndex("TC_IdPersonal", "TN_IdTipo")
                        .IsUnique();

                    b.ToTable("THBT_A_PersonalTipoMantenimiento");
                });

            modelBuilder.Entity("Habitia.Models.Publicacion", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TC_Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TC_Especificaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("TF_FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TF_FechaServicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdCategoria")
                        .HasColumnType("int");

                    b.Property<decimal>("TN_Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TN_Tipo")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TT_HoraFinServicio")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TT_HoraInicioServicio")
                        .HasColumnType("time");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TN_IdCategoria");

                    b.ToTable("THBT_A_Publicacion");
                });

            modelBuilder.Entity("Habitia.Models.ResenaPublicacion", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TF_FechaResena")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Calificacion")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdPublicacion")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TN_IdPublicacion");

                    b.ToTable("THBT_A_ResenaPublicacion");
                });

            modelBuilder.Entity("Habitia.Models.Reserva", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("TF_FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdDisponibilidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TN_IdDisponibilidad");

                    b.HasIndex("TN_IdVivienda");

                    b.ToTable("THBT_A_Reserva");
                });

            modelBuilder.Entity("Habitia.Models.Vivienda", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_CantidadInquilinos")
                        .HasColumnType("int");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_Tipo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_Numero")
                        .IsUnique();

                    b.ToTable("THBT_A_Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.ViviendaUsuario", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_ViveAhi")
                        .HasColumnType("bit");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.Property<int>("TN_TipoRelacion")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TN_IdVivienda");

                    b.ToTable("THBT_A_ViviendaUsuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("THBT_A_Rol", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("THBT_A_RolClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("THBT_A_UsuarioClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("THBT_A_UsuarioLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("THBT_A_UsuarioRol", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("THBT_A_UsuarioToken", (string)null);
                });

            modelBuilder.Entity("Habitia.Models.Acceso.Acceso", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Acceso.Autorizacion", "Autorizacion")
                        .WithMany("Accesos")
                        .HasForeignKey("TN_IdAutorizacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Habitia.Models.Acceso.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("TN_IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Habitia.Models.Acceso.Visitante", "Visitante")
                        .WithMany()
                        .HasForeignKey("TN_IdVisitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany()
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autorizacion");

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");

                    b.Navigation("Visitante");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.Acceso.Autorizacion", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Acceso.Visitante", "Visitante")
                        .WithMany("Autorizaciones")
                        .HasForeignKey("TN_IdVisitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany()
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Visitante");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.Acceso.Vehiculo", b =>
                {
                    b.HasOne("Habitia.Models.Acceso.Visitante", "Visitante")
                        .WithMany("Vehiculos")
                        .HasForeignKey("TN_IdVisitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("Habitia.Models.AreaComun", b =>
                {
                    b.HasOne("Habitia.Models.Catalogos.TipoArea", "Tipo")
                        .WithMany("Areas")
                        .HasForeignKey("TN_IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Habitia.Models.AreaComunFoto", b =>
                {
                    b.HasOne("Habitia.Models.AreaComun", "AreaComun")
                        .WithMany("Fotos")
                        .HasForeignKey("TN_IdAreaComun")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaComun");
                });

            modelBuilder.Entity("Habitia.Models.CodigoVerificacion", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Habitia.Models.DisponibilidadArea", b =>
                {
                    b.HasOne("Habitia.Models.AreaComun", "AreaComun")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("TN_IdAreaComun")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaComun");
                });

            modelBuilder.Entity("Habitia.Models.Documentos.Asamblea", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Habitia.Models.Documentos.Documento", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Catalogos.CategoriaDocumento", "Categoria")
                        .WithMany("Documentos")
                        .HasForeignKey("TN_IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Habitia.Models.Documentos.DocumentoAsamblea", b =>
                {
                    b.HasOne("Habitia.Models.Documentos.Asamblea", "Asamblea")
                        .WithMany("Documentos")
                        .HasForeignKey("TN_IdAsamblea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Documentos.Documento", "Documento")
                        .WithMany("Asambleas")
                        .HasForeignKey("TN_IdDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asamblea");

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("Habitia.Models.Documentos.ParticipanteAsamblea", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Documentos.Asamblea", "Asamblea")
                        .WithMany("Participantes")
                        .HasForeignKey("TN_IdAsamblea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asamblea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_Cargo", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Residente")
                        .WithMany()
                        .HasForeignKey("TC_IdResidente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Financiero.THBT_CAT_EstadoCargo", "EstadoCargo")
                        .WithMany()
                        .HasForeignKey("TN_IdEstadoCargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Financiero.THBT_CAT_TipoCargo", "TipoCargo")
                        .WithMany()
                        .HasForeignKey("TN_IdTipoCargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Financiero.THBT_CAT_TipoRecargo", "TipoRecargo")
                        .WithMany()
                        .HasForeignKey("TN_IdTipoRecargo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany()
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EstadoCargo");

                    b.Navigation("Residente");

                    b.Navigation("TipoCargo");

                    b.Navigation("TipoRecargo");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_CargoRecurrente", b =>
                {
                    b.HasOne("Habitia.Models.Financiero.THBT_CAT_TipoCargo", "TipoCargo")
                        .WithMany()
                        .HasForeignKey("TN_IdTipoCargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Financiero.THBT_CAT_TipoRecargo", "TipoRecargo")
                        .WithMany()
                        .HasForeignKey("TN_IdTipoRecargo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoCargo");

                    b.Navigation("TipoRecargo");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_CargoRecurrenteResidente", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Residente")
                        .WithMany()
                        .HasForeignKey("TC_IdResidente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Financiero.THBT_A_CargoRecurrente", "CargoRecurrente")
                        .WithMany("Residentes")
                        .HasForeignKey("TN_IdCargoRecurrente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany()
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CargoRecurrente");

                    b.Navigation("Residente");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_Pago", b =>
                {
                    b.HasOne("Habitia.Models.Financiero.THBT_A_Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("TN_IdCargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Financiero.THBT_CAT_MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("TN_IdMetodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_Recargo", b =>
                {
                    b.HasOne("Habitia.Models.Financiero.THBT_A_Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("TN_IdCargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Financiero.THBT_CAT_TipoRecargo", "TipoRecargo")
                        .WithMany()
                        .HasForeignKey("TN_IdTipoRecargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("TipoRecargo");
                });

            modelBuilder.Entity("Habitia.Models.ImagenPublicacion", b =>
                {
                    b.HasOne("Habitia.Models.Publicacion", null)
                        .WithMany("Imagenes")
                        .HasForeignKey("TN_IdPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Habitia.Models.Incidencia", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", null)
                        .WithMany("Incidencias")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.AreaComun", "AreaComun")
                        .WithMany()
                        .HasForeignKey("TN_IdAreaComun")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany()
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AreaComun");

                    b.Navigation("Usuario");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.Mantenimiento", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "PersonalAsignado")
                        .WithMany()
                        .HasForeignKey("TC_IdPersonalAsignado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.AreaComun", "AreaComun")
                        .WithMany()
                        .HasForeignKey("TN_IdAreaComun")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Habitia.Models.Incidencia", "Incidencia")
                        .WithOne("Mantenimiento")
                        .HasForeignKey("Habitia.Models.Mantenimiento", "TN_IdIncidencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Catalogos.TipoMantenimiento", "Tipo")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("TN_IdTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaComun");

                    b.Navigation("Incidencia");

                    b.Navigation("PersonalAsignado");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Habitia.Models.PersonalTipoMantenimiento", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Personal")
                        .WithMany()
                        .HasForeignKey("TC_IdPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Catalogos.TipoMantenimiento", "Tipo")
                        .WithMany("PersonalAsignado")
                        .HasForeignKey("TN_IdTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Habitia.Models.Publicacion", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Catalogos.THBT_CAT_CategoriaPublicacion", "Categoria")
                        .WithMany("Publicaciones")
                        .HasForeignKey("TN_IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Habitia.Models.ResenaPublicacion", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Publicacion", "Publicacion")
                        .WithMany("Resenas")
                        .HasForeignKey("TN_IdPublicacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Habitia.Models.Reserva", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.DisponibilidadArea", "Disponibilidad")
                        .WithMany("Reservas")
                        .HasForeignKey("TN_IdDisponibilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany()
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disponibilidad");

                    b.Navigation("Usuario");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.ViviendaUsuario", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany("Viviendas")
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany("Usuarios")
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Habitia.Models.Acceso.Autorizacion", b =>
                {
                    b.Navigation("Accesos");
                });

            modelBuilder.Entity("Habitia.Models.Acceso.Visitante", b =>
                {
                    b.Navigation("Autorizaciones");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Habitia.Models.ApplicationUser", b =>
                {
                    b.Navigation("Incidencias");

                    b.Navigation("Reservas");

                    b.Navigation("Viviendas");
                });

            modelBuilder.Entity("Habitia.Models.AreaComun", b =>
                {
                    b.Navigation("Disponibilidades");

                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.CategoriaDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.THBT_CAT_CategoriaPublicacion", b =>
                {
                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.TipoArea", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.TipoMantenimiento", b =>
                {
                    b.Navigation("Mantenimientos");

                    b.Navigation("PersonalAsignado");
                });

            modelBuilder.Entity("Habitia.Models.DisponibilidadArea", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Habitia.Models.Documentos.Asamblea", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Habitia.Models.Documentos.Documento", b =>
                {
                    b.Navigation("Asambleas");
                });

            modelBuilder.Entity("Habitia.Models.Financiero.THBT_A_CargoRecurrente", b =>
                {
                    b.Navigation("Residentes");
                });

            modelBuilder.Entity("Habitia.Models.Incidencia", b =>
                {
                    b.Navigation("Mantenimiento");
                });

            modelBuilder.Entity("Habitia.Models.Publicacion", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("Habitia.Models.Vivienda", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
