// <auto-generated />
using System;
using Habitia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Habitia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729154806_05-Accesos2")]
    partial class _05Accesos2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Habitia.Models.Acceso", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TF_FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TF_FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TN_IdAutorizacion")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdVehiculo")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVisitante")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TF_FechaIngreso");

                    b.HasIndex("TF_FechaSalida");

                    b.HasIndex("TN_IdAutorizacion")
                        .IsUnique()
                        .HasFilter("[TN_IdAutorizacion] IS NOT NULL");

                    b.HasIndex("TN_IdVehiculo");

                    b.HasIndex("TN_IdVisitante");

                    b.HasIndex("TN_IdVivienda");

                    b.ToTable("THBT_A_Acceso");
                });

            modelBuilder.Entity("Habitia.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC_Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TC_FotoPerfil")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TC_Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TC_Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_TipoIdentificacion")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("THBT_A_Usuario", (string)null);
                });

            modelBuilder.Entity("Habitia.Models.AreaComun", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TN_AnticipacionMinima")
                        .HasColumnType("int");

                    b.Property<int>("TN_Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdTipo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdTipo");

                    b.ToTable("THBT_A_AreaComun");
                });

            modelBuilder.Entity("Habitia.Models.AreaComunFoto", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TN_IdAreaComun")
                        .HasColumnType("int");

                    b.Property<int>("TN_Orden")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdAreaComun");

                    b.ToTable("THBT_A_AreaComunFoto");
                });

            modelBuilder.Entity("Habitia.Models.Autorizacion", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TF_FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TF_FechaVisita")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVisitante")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_Codigo")
                        .IsUnique();

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TF_FechaVencimiento");

                    b.HasIndex("TN_Estado");

                    b.HasIndex("TN_IdVisitante");

                    b.HasIndex("TN_IdVivienda");

                    b.ToTable("THBT_A_Autorizacion");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.THBT_CAT_CategoriaPublicacion", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_CAT_CategoriaPublicacion");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.TipoArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("THBT_CAT_TipoArea");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.TipoMantenimiento", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_Nombre")
                        .IsUnique();

                    b.ToTable("THBT_CAT_TipoMantenimiento");
                });

            modelBuilder.Entity("Habitia.Models.DisponibilidadArea", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("TB_Reservado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TF_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TF_HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TF_HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("TN_Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdAreaComun")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdAreaComun");

                    b.ToTable("THBT_A_DisponibilidadArea");
                });

            modelBuilder.Entity("Habitia.Models.ExpiracionReserva", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<int>("TN_Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_Tipo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_A_ExpiracionReserva");
                });

            modelBuilder.Entity("Habitia.Models.ImagenPublicacion", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TN_IdPublicacion")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdPublicacion");

                    b.ToTable("THBT_A_ImagenPublicacion");
                });

            modelBuilder.Entity("Habitia.Models.Incidencia", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MantenimientoTN_Id")
                        .HasColumnType("int");

                    b.Property<string>("TC_Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_ImagenUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TC_Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TF_FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdAreaComun")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.Property<int?>("TN_Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("TN_Responsabilidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_Tipo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("MantenimientoTN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TF_FechaRegistro");

                    b.HasIndex("TN_Estado");

                    b.HasIndex("TN_IdAreaComun");

                    b.HasIndex("TN_IdVivienda");

                    b.HasIndex("TN_Responsabilidad");

                    b.ToTable("THBT_A_Incidencia");
                });

            modelBuilder.Entity("Habitia.Models.Mantenimiento", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TC_IdPersonalAsignado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("TF_FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TF_FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int?>("TN_IdAreaComun")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdIncidencia")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdTipo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdPersonalAsignado");

                    b.HasIndex("TN_Estado");

                    b.HasIndex("TN_IdAreaComun");

                    b.HasIndex("TN_IdIncidencia")
                        .IsUnique();

                    b.HasIndex("TN_IdTipo");

                    b.ToTable("THBT_A_Mantenimiento");
                });

            modelBuilder.Entity("Habitia.Models.Publicacion", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TC_Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TC_Especificaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("TF_FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TF_FechaServicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdCategoria")
                        .HasColumnType("int");

                    b.Property<decimal>("TN_Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TN_Tipo")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TT_HoraFinServicio")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TT_HoraInicioServicio")
                        .HasColumnType("time");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TN_IdCategoria");

                    b.ToTable("THBT_A_Publicacion");
                });

            modelBuilder.Entity("Habitia.Models.ResenaPublicacion", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TF_FechaResena")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Calificacion")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdPublicacion")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TN_IdPublicacion");

                    b.ToTable("THBT_A_ResenaPublicacion");
                });

            modelBuilder.Entity("Habitia.Models.Reserva", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TC_Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("TF_FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdDisponibilidad")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TN_IdDisponibilidad");

                    b.HasIndex("TN_IdVivienda");

                    b.ToTable("THBT_A_Reserva");
                });

            modelBuilder.Entity("Habitia.Models.Vehiculo", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TC_Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TC_Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TN_IdVisitante")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TN_IdVisitante");

                    b.ToTable("THBT_A_Vehiculo");
                });

            modelBuilder.Entity("Habitia.Models.Visitante", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_Estado")
                        .HasColumnType("bit");

                    b.Property<string>("TC_Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TC_Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TN_TipoIdentificacion")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.ToTable("THBT_A_Visitante");
                });

            modelBuilder.Entity("Habitia.Models.Vivienda", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<string>("TC_Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_CantidadInquilinos")
                        .HasColumnType("int");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_Tipo")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_Numero")
                        .IsUnique();

                    b.ToTable("THBT_A_Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.ViviendaUsuario", b =>
                {
                    b.Property<int>("TN_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TN_Id"));

                    b.Property<bool>("TB_ViveAhi")
                        .HasColumnType("bit");

                    b.Property<string>("TC_IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TF_FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TN_Estado")
                        .HasColumnType("int");

                    b.Property<int>("TN_IdVivienda")
                        .HasColumnType("int");

                    b.Property<int>("TN_TipoRelacion")
                        .HasColumnType("int");

                    b.HasKey("TN_Id");

                    b.HasIndex("TC_IdUsuario");

                    b.HasIndex("TN_IdVivienda");

                    b.ToTable("THBT_A_ViviendaUsuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("THBT_A_Rol", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("THBT_A_RolClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("THBT_A_UsuarioClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("THBT_A_UsuarioLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("THBT_A_UsuarioRol", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("THBT_A_UsuarioToken", (string)null);
                });

            modelBuilder.Entity("Habitia.Models.Acceso", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Autorizacion", "Autorizacion")
                        .WithMany("Accesos")
                        .HasForeignKey("TN_IdAutorizacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Habitia.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("TN_IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Habitia.Models.Visitante", "Visitante")
                        .WithMany()
                        .HasForeignKey("TN_IdVisitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany()
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autorizacion");

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");

                    b.Navigation("Visitante");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.AreaComun", b =>
                {
                    b.HasOne("Habitia.Models.Catalogos.TipoArea", "Tipo")
                        .WithMany("Areas")
                        .HasForeignKey("TN_IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Habitia.Models.AreaComunFoto", b =>
                {
                    b.HasOne("Habitia.Models.AreaComun", "AreaComun")
                        .WithMany("Fotos")
                        .HasForeignKey("TN_IdAreaComun")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaComun");
                });

            modelBuilder.Entity("Habitia.Models.Autorizacion", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Visitante", "Visitante")
                        .WithMany("Autorizaciones")
                        .HasForeignKey("TN_IdVisitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany()
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Visitante");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.DisponibilidadArea", b =>
                {
                    b.HasOne("Habitia.Models.AreaComun", "AreaComun")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("TN_IdAreaComun")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaComun");
                });

            modelBuilder.Entity("Habitia.Models.ImagenPublicacion", b =>
                {
                    b.HasOne("Habitia.Models.Publicacion", null)
                        .WithMany("Imagenes")
                        .HasForeignKey("TN_IdPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Habitia.Models.Incidencia", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", null)
                        .WithMany("Incidencias")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Habitia.Models.Mantenimiento", "Mantenimiento")
                        .WithMany()
                        .HasForeignKey("MantenimientoTN_Id");

                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.AreaComun", "AreaComun")
                        .WithMany()
                        .HasForeignKey("TN_IdAreaComun")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany()
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AreaComun");

                    b.Navigation("Mantenimiento");

                    b.Navigation("Usuario");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.Mantenimiento", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "PersonalAsignado")
                        .WithMany()
                        .HasForeignKey("TC_IdPersonalAsignado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.AreaComun", "AreaComun")
                        .WithMany()
                        .HasForeignKey("TN_IdAreaComun")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Habitia.Models.Incidencia", "Incidencia")
                        .WithMany()
                        .HasForeignKey("TN_IdIncidencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Catalogos.TipoMantenimiento", "Tipo")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("TN_IdTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaComun");

                    b.Navigation("Incidencia");

                    b.Navigation("PersonalAsignado");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Habitia.Models.Publicacion", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Catalogos.THBT_CAT_CategoriaPublicacion", "Categoria")
                        .WithMany("Publicaciones")
                        .HasForeignKey("TN_IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Habitia.Models.ResenaPublicacion", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Publicacion", "Publicacion")
                        .WithMany("Resenas")
                        .HasForeignKey("TN_IdPublicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Habitia.Models.Reserva", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.DisponibilidadArea", "Disponibilidad")
                        .WithMany("Reservas")
                        .HasForeignKey("TN_IdDisponibilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany()
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disponibilidad");

                    b.Navigation("Usuario");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Habitia.Models.Vehiculo", b =>
                {
                    b.HasOne("Habitia.Models.Visitante", "Visitante")
                        .WithMany("Vehiculos")
                        .HasForeignKey("TN_IdVisitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("Habitia.Models.ViviendaUsuario", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", "Usuario")
                        .WithMany("Viviendas")
                        .HasForeignKey("TC_IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.Vivienda", "Vivienda")
                        .WithMany("Usuarios")
                        .HasForeignKey("TN_IdVivienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vivienda");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Habitia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Habitia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Habitia.Models.ApplicationUser", b =>
                {
                    b.Navigation("Incidencias");

                    b.Navigation("Reservas");

                    b.Navigation("Viviendas");
                });

            modelBuilder.Entity("Habitia.Models.AreaComun", b =>
                {
                    b.Navigation("Disponibilidades");

                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Habitia.Models.Autorizacion", b =>
                {
                    b.Navigation("Accesos");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.THBT_CAT_CategoriaPublicacion", b =>
                {
                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.TipoArea", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Habitia.Models.Catalogos.TipoMantenimiento", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("Habitia.Models.DisponibilidadArea", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Habitia.Models.Publicacion", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("Habitia.Models.Visitante", b =>
                {
                    b.Navigation("Autorizaciones");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Habitia.Models.Vivienda", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
